-- 코드를 입력하세요
SELECT *
FROM (
    SELECT CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) /100) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
    WHERE CAR_ID NOT IN (SELECT CAR_ID 
                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01')
        AND C.DURATION_TYPE LIKE '30일%'
        AND (C.CAR_TYPE = 'SUV' OR C.CAR_TYPE = '세단')) D
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;