-- 코드를 입력하세요
SELECT INS.ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_INS INS
JOIN (SELECT ANIMAL_ID, SEX_UPON_OUTCOME FROM ANIMAL_OUTS) OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE SEX_UPON_INTAKE != SEX_UPON_OUTCOME