-- 코드를 입력하세요
SELECT NAME, DATETIME
FROM ANIMAL_INS INS
LEFT OUTER JOIN (SELECT ANIMAL_ID FROM ANIMAL_OUTS) OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE OUTS.ANIMAL_ID IS NULL
ORDER BY DATETIME
LIMIT 3;