-- 코드를 입력하세요
SELECT FOOD_PRODUCT.PRODUCT_ID, PRODUCT_NAME, AMOUNTS * PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNTS
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE < '2022-06-01'
    GROUP BY PRODUCT_ID) MAY_ORDER ON MAY_ORDER.PRODUCT_ID = FOOD_PRODUCT.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FOOD_PRODUCT.PRODUCT_ID;